import os
import sys
import json

import copy

from util import evaluate_news

dataset_name = 'goodnews'

# generated by count_entity_have_person.py

tmp_annotation_file = '.tmp_annotation.json'
tmp_result_file = '.tmp_result.json'

def load_json(file):
    with open(file, 'r') as f:
        return json.load(f)

def evaluate_person(annotation_file, result_file):
    split_file = f'/media/wentian/sdb1/work/news_caption_fairseq/data/person_split_{dataset_name}.json'

    split = load_json(split_file)
    ann = load_json(annotation_file)
    res = load_json(result_file)

    for i, key in enumerate(['have_person', 'no_person']):
        image_id_list = split[key]
        image_id_set = set(image_id_list)
        d1 = copy.deepcopy(ann)
        d1['images'] = list(filter(lambda x: x['id'] in image_id_set, d1['images']))
        d1['annotations'] = list(filter(lambda x: x['image_id'] in image_id_set, d1['annotations']))
        d2 = list(filter(lambda x: x['image_id'] in image_id_set, res))

        split_annotation_file = tmp_annotation_file + f'_{i}'
        split_result_file = tmp_result_file + f'_{i}'
        with open(split_annotation_file, 'w') as f:
            json.dump(d1, f)
        with open(split_result_file, 'w') as f:
            json.dump(d2, f)
        print(key, '{} images'.format(len(d2)))
        metrics = evaluate_news(split_annotation_file, split_result_file, return_imgscores=False)
        print(metrics)


if __name__ == '__main__':
    dataset_name = 'goodnews'
    ann_file = r'/media/wentian/sdb1/work/news_caption_fairseq/save/checkpoint_transformer2_conv_mm_image/validation_results_test-small/annotation.json'
    # res_file = r'/media/wentian/sdb1/work/news_caption_fairseq/save/checkpoint_transformer2_conv_mm_image/validation_results_test-small/result_50_204787.json'
    res_file = r'/media/wentian/sdb1/work/news_caption_fairseq/save/checkpoint_transformer2_conv_mm_text/validation_results_test-small/result_30_122871.json'

    # dataset_name = 'nytimes'
    # ann_file = r'/media/wentian/sdb1/work/news_caption_fairseq/save/checkpoint_transformer2_conv_mm_text_nytimes/validation_results_test-small/annotation.json'
    # res_file = r'/media/wentian/sdb1/work/news_caption_fairseq/save/checkpoint_transformer2_conv_mm_text_nytimes/validation_results_test-small/result_6_24576.json'

    metrics = evaluate_news(ann_file, res_file)
    print(metrics)
    evaluate_person(ann_file, res_file)